name       : peek
version    : 1.3.0
release    : 17
source     :
    - https://github.com/phw/peek/archive/1.3.0.tar.gz : 0d20741663e9a173151d8371df3cb90f8f542033640ce99a4863803cd0f32cb4
license    : GPL-3.0
component  : multimedia.video
summary    : A simple tool that allows you to record short animated GIF images from your screen
description: |
    A simple tool that allows you to record short animated GIF images from your screen.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(keybinder-3.0)
    - pkgconfig(libavformat)
    - gifski
    - vala
rundeps    :
    - gifski
    - imagemagick
setup      : |
    %cmake . -DBUILD_TESTS=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test

