name       : peek
version    : 0.9.1
release    : 6
source     :
    - https://github.com/phw/peek/archive/v0.9.1.tar.gz : dc0531f8f090a0ff0af69c3554b3bb9c297eb6a6e7405b325aaf20aa9c5f365b
license    : GPL-3.0
component  : multimedia.video
summary    : A simple tool that allows you to record short animated GIF images from your screen.
description: |
    A simple tool that allows you to record short animated GIF images from your screen.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ImageMagick)
    - pkgconfig(libavformat)
    - vala
rundeps    :
    - imagemagick
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
