name       : peek
version    : 1.2.0
release    : 11
source     :
    - https://github.com/phw/peek/archive/1.2.0.tar.gz : d6117baca6810d846831653023eb0517138a435a0f85fea9fc1c28421c0ccb2b
license    : GPL-3.0
component  : multimedia.video
summary    : A simple tool that allows you to record short animated GIF images from your screen.
description: |
    A simple tool that allows you to record short animated GIF images from your screen.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(keybinder-3.0)
    - pkgconfig(libavformat)
    - vala
rundeps    :
    - imagemagick
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
