name       : peek
version    : 1.3.1
release    : 23
source     :
    - git|https://github.com/phw/peek.git : 4967e1854cd82b730ab3beb8faf5faa4fadea4a0
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : A simple tool that allows you to record short animated GIF images from
    your screen
description: |
    A simple tool that allows you to record short animated GIF images from your screen.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(keybinder-3.0)
    - pkgconfig(libavformat)
    - gifski
    - vala
rundeps    :
    - gifski
    - imagemagick
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-compilation-under-Vala-0.45-and-above.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
