name       : peek
version    : 0.7.2
release    : 1
source     :
    - https://github.com/phw/peek/archive/v0.7.2.tar.gz : f5e65767613d408abccb7da6f3ecd237448a8a92efefedc012a08fa2ba092f52
license    : GPL-3.0
component  : multimedia.video
summary    : A simple tool that allows you to record short animated GIF images from your screen.
description: |
    A simple tool that allows you to record short animated GIF images from your screen.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ImageMagick)
    - pkgconfig(libavformat)
    - vala
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
