name       : peek
version    : 1.2.1
release    : 13
source     :
    - https://github.com/phw/peek/archive/1.2.1.tar.gz : 7035ad6817306bf93b0052bf989120793e26b3fbcba51dda3cdf345342214af5
license    : GPL-3.0
component  : multimedia.video
summary    : A simple tool that allows you to record short animated GIF images from
    your screen.
description: |
    A simple tool that allows you to record short animated GIF images from your screen.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(keybinder-3.0)
    - pkgconfig(libavformat)
    - vala
rundeps    :
    - imagemagick
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
