name       : peek
version    : 1.0.1
release    : 8
source     :
    - https://github.com/phw/peek/archive/v1.0.1.tar.gz : 7913664d33756b0e94fc190e1762eba581fcb4bf7100965df3417e90d6254ae3
license    : GPL-3.0
component  : multimedia.video
summary    : A simple tool that allows you to record short animated GIF images from your screen.
description: |
    A simple tool that allows you to record short animated GIF images from your screen.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(keybinder-3.0)
    - pkgconfig(libavformat)
    - vala
rundeps    :
    - imagemagick
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
