name       : peek
version    : 1.1.0
release    : 10
source     :
    - https://github.com/phw/peek/archive/1.1.0.tar.gz : 3e34be130c43653e849efe9e3e08e446880c11aaf47ec4c62b54c5c5092f4cf9
license    : GPL-3.0
component  : multimedia.video
summary    : A simple tool that allows you to record short animated GIF images from your screen.
description: |
    A simple tool that allows you to record short animated GIF images from your screen.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(keybinder-3.0)
    - pkgconfig(libavformat)
    - vala
rundeps    :
    - imagemagick
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
