name       : peek
version    : 1.0.0
release    : 7
source     :
    - https://github.com/phw/peek/archive/v1.0.0.tar.gz : 1430a92148a066185051664e3bd20a5ce0cc6c97345d1b2a959b698b291ea1fb
license    : GPL-3.0
component  : multimedia.video
summary    : A simple tool that allows you to record short animated GIF images from your screen.
description: |
    A simple tool that allows you to record short animated GIF images from your screen.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(keybinder-3.0)
    - pkgconfig(libavformat)
    - vala
rundeps    :
    - imagemagick
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
