name       : peek
version    : 0.8.0
release    : 3
source     :
    - https://github.com/phw/peek/archive/v0.8.0.tar.gz : 45261ecd3f1891962441266e723a50a7ec81ee00a699c2db64bdde5e6c01aaa9
license    : GPL-3.0
component  : multimedia.video
summary    : A simple tool that allows you to record short animated GIF images from
    your screen.
description: |
    A simple tool that allows you to record short animated GIF images from your screen.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ImageMagick)
    - pkgconfig(libavformat)
    - vala
rundeps    :
    - imagemagick
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
