name       : peek
version    : 1.0.3
release    : 9
source     :
    - https://github.com/phw/peek/archive/v1.0.3.tar.gz : bedb23a4da0b6f5c9e247a383435202ff7307347f39cd8816d256b3390a4c1ae
license    : GPL-3.0
component  : multimedia.video
summary    : A simple tool that allows you to record short animated GIF images from your screen.
description: |
    A simple tool that allows you to record short animated GIF images from your screen.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(keybinder-3.0)
    - pkgconfig(libavformat)
    - vala
rundeps    :
    - imagemagick
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
